name: Build and Release Cross-Platform CLI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile --name pmclient main.py

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: |
            dist/pmclient*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
